//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNCRemotew {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class RemoteCNC_config : global::System.Configuration.ApplicationSettingsBase {
        
        private static RemoteCNC_config defaultInstance = ((RemoteCNC_config)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new RemoteCNC_config())));
        
        public static RemoteCNC_config Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.31.250")]
        public string database_ip {
            get {
                return ((string)(this["database_ip"]));
            }
            set {
                this["database_ip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("chk")]
        public string database_user {
            get {
                return ((string)(this["database_user"]));
            }
            set {
                this["database_user"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12345678")]
        public string database_pass {
            get {
                return ((string)(this["database_pass"]));
            }
            set {
                this["database_pass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CNC状态 {
            get {
                return ((bool)(this["CNC状态"]));
            }
            set {
                this["CNC状态"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool pakage {
            get {
                return ((bool)(this["pakage"]));
            }
            set {
                this["pakage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("hanhai_manufacture")]
        public string database_name {
            get {
                return ((string)(this["database_name"]));
            }
            set {
                this["database_name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("瀚海")]
        public string Factory {
            get {
                return ((string)(this["Factory"]));
            }
            set {
                this["Factory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("work_cnc_task_list")]
        public string sheet_cnc_task {
            get {
                return ((string)(this["sheet_cnc_task"]));
            }
            set {
                this["sheet_cnc_task"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("order_element_online")]
        public string sheet_element {
            get {
                return ((string)(this["sheet_element"]));
            }
            set {
                this["sheet_element"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("order_contract_internal")]
        public string sheet_contract {
            get {
                return ((string)(this["sheet_contract"]));
            }
            set {
                this["sheet_contract"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gprinter GP-9025T")]
        public string printer1 {
            get {
                return ((string)(this["printer1"]));
            }
            set {
                this["printer1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string printer2 {
            get {
                return ((string)(this["printer2"]));
            }
            set {
                this["printer2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string printer3 {
            get {
                return ((string)(this["printer3"]));
            }
            set {
                this["printer3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("123456")]
        public string CNC1 {
            get {
                return ((string)(this["CNC1"]));
            }
            set {
                this["CNC1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CNC2 {
            get {
                return ((string)(this["CNC2"]));
            }
            set {
                this["CNC2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CNC3 {
            get {
                return ((string)(this["CNC3"]));
            }
            set {
                this["CNC3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool 补打工位状态 {
            get {
                return ((bool)(this["补打工位状态"]));
            }
            set {
                this["补打工位状态"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public string cnc_code {
            get {
                return ((string)(this["cnc_code"]));
            }
            set {
                this["cnc_code"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public string reprint_code {
            get {
                return ((string)(this["reprint_code"]));
            }
            set {
                this["reprint_code"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("work_cnc_before_layout_temporary")]
        public string sheet_temporary {
            get {
                return ((string)(this["sheet_temporary"]));
            }
            set {
                this["sheet_temporary"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string choose_state {
            get {
                return ((string)(this["choose_state"]));
            }
            set {
                this["choose_state"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool 质检工位状态 {
            get {
                return ((bool)(this["质检工位状态"]));
            }
            set {
                this["质检工位状态"] = value;
            }
        }
    }
}
